apiVersion: v1
kind: Pod
metadata:
  name: obj1
  namespace: test
  labels:
    env: prod
  annotations:
    env: prodnew
spec:
  containers:
  - name: con1
    image: nginx
    ports:
    - containerPort: 80
  - name: con2
    image: centos
    command: ['/bin/bash','-c','while true;do echo hello;sleep 1;done']
