apiVersion: v1
kind: Pod
metadata:
  name: obj2 
  namespace: test
spec:
  
  containers:
  - name: c1
    image: centos
    env:
    - name: var1
      value: value1
    - name: var2
      value: value2
    command: ['/bin/bash','-c','sleep 600']  
    resources: 
      requests:
        cpu: .5m
        memory: 10m
      limits:
        cpu: 1m
        memory: 20m
